### ISSUE TITLE
Issue：插件使用无法做动效

### ISSUE THREAD

**Issue by CodeEngieer** [sunsvip/PSD2UGUI_X#1]
国人研发的就用中文提问题了，我是一名资深UI动效师，其实我头疼Unity里解析PSD文件很久了。我想提的问题是
1. Animation创建动画的时候，由于你用的是脚本生成，prefab控制动画帧的时候只能控制脚本，抠脚本也没什么用
2. 我想着导出prefab的image，先不考虑水印的问题。导出之后又是零散图，这跟我psd导出为图片有什么区别然后对照效果图拼UI？用起来我就感觉很鸡肋

**Comment by CodeEngieer** [comment]
还有不是为了拼UI而拼UI，拼UI的目的是添加效果shader或者做UI动画，如果导出解析的psd生成的prefab既不能拼动画又不能附加shader，那生成这个又什么意义呢？

**Comment by sunsvip** [comment]
每一个问题都直击灵魂，我竟然一个都答不上来。资深UI动效师，这个工具甚至跟你的工作内容不在一个工作流，又何谈影响动效师做动效呢？此工具是一键生成拼好的UI预制体，动效师拿着预制体该怎么key怎么key。
我猜你是没看博文用法，让你们程序去生成预制体吧。
