### ISSUE TITLE
Aspose破解问题

### ISSUE THREAD

**Issue by xiaopizi19** [sunsvip/PSD2UGUI_X#2]
您好，请问下您能否提供一个过期的Aspose证书呢

**Comment by sunsvip** [comment]
[Aspose证书/密钥获取：](https://purchase.aspose.com/pricing/psd/net/?_gl=1*12zsgxi*_gcl_au*MTU5MDI2MzQ1Ni4xNzEyODkyNzUx*_ga*MTI3NjA0ODI0MS4xNzAxMjI1NTY4*_ga_W0DG8XJWKL*MTcxODc4MTUxMS4yOC4xLjE3MTg3ODQ5MTMuNjAuMC43NjQxMTI3ODQ.)
